144 fix extension needing page refresh on opening another email
cs481-ekh/s24-gone-phishin pull request #176
Opened 2024-04-07 01:56 UTC by SorrenMosher

Extension now scans emails automatically upon being opened.
Extension now flushes scan results when navigating back to the inbox.

2024-04-07 02:07 UTC, kdoster approved these changes

2024-04-07 03:31 UTC, Subpoened-peon approved these changes

2024-04-07 22:58 UTC, torisimon2 requested changes
There's an issue where if the email is listed under a label/in a folder it won't scan. I also encountered an issue where if I clicked between emails too fast it would display the previous email's risk score

2024-04-09 02:39 UTC, torisimon2 approved these changes

2024-04-09 03:59 UTC, merged